### PR TITLE
Added vertx-auth-webauthn4j module

### PR DESCRIPTION
**Pull request by FroMage**
This is the new WebAuthn4J module that will come in its own PR.

### CODE REVIEW

**Comment by tsegismont** [comment]
Thanks @FroMage 

In case you missed it, there are other modules that must be updated: https://github.com/vert-x3/vertx-stack?tab=readme-ov-file#adding-a-new-module-to-the-stack

**Comment by FroMage** [comment]
I did miss it indeed. Wow.

**Comment by FroMage** [comment]
> Add it to the website in [vertx-web-site](https://github.com/vertx-web-site/vertx-web-site.github.io):
> Edit the docs summary page docs/metadata/<version>.jsx, use Tech Preview label

That doesn't seem to be enough, I've added it in the `vertx5` branch in `5.0.0-SNAPSHOT.jsx`:

```
insert(docs, "vertx-auth-webauthn",
  {
    id: "vertx-auth-webauthn4j",
    name: "Webauthn Auth with WebAuthn4J",
    description: "FIDO2 WebAuthn (password-less) wrapper for WebAuthn4J.",
    category: "authentication-and-authorization",
    href: "/vertx-auth-webauthn4j/java/",
    repository: "https://github.com/eclipse-vertx/vertx-auth/tree/master/vertx-auth-webauthn4j",
    edit: "https://github.com/eclipse-vertx/vertx-auth/tree/master/vertx-auth-webauthn4j/src/main/asciidoc",
    label: "Technical Preview"
  }
 )

```

But I get a 404 when I build the site locally and go to http://localhost:3000/docs/vertx-auth-webauthn4j/java/ although I do see it listed in http://localhost:3000/docs/

Perhaps it's fine and it's because it's trying to look it up from github where it's not merged yet? Or perhaps I need to do something else for docs to be published?

**Comment by tsegismont** [comment]
Have you run `npm run update-docs` ?

@michel-kraemer any other idea?

**Comment by michel-kraemer** [comment]
@FroMage I've downloaded the stack docs zip built today (2024-11-10) from [1] but I cannot find a `vertx-auth-webauthn4j` folder inside of it. If you've already added the module to the stack, you may have to wait for the next nightly build.

Also, please submit your PR to my fork [2], which contains the latest version of the website. We will merge this fork into the main repository as soon as Vert.x 5 is released. The `vertx5` branch is outdated and will be removed soon.

I hope this helps. Let me know if you have questions.

Cheers,
Michel

[1] https://s01.oss.sonatype.org/content/repositories/snapshots/io/vertx/vertx-stack-docs/5.0.0-SNAPSHOT/
[2] https://github.com/michel-kraemer/vertx-web-site.github.io

**Comment by tsegismont** [comment]
Thank you @michel-kraemer !

**Pull request merged**
