### PR TITLE
update netty to 4.1.66.Final - fixes random upload failure

### PR DESCRIPTION
**Pull request by DemonicTutor**
Motivation:

see: issue in vert.x core: https://github.com/eclipse-vertx/vert.x/issues/3949

Conformance:

Your commits should be signed and you should have signed the Eclipse Contributor Agreement as explained in https://github.com/eclipse/vert.x/blob/master/CONTRIBUTING.md
Please also make sure you adhere to the code style guidelines: https://github.com/vert-x3/wiki/wiki/Vert.x-code-style-guidelines

### CODE REVIEW

**Comment by DemonicTutor** [comment]
dunno why `eclipsefdn/eca ` is failing? worked in the past

**Comment by DemonicTutor** [comment]
~3h and still not in mvn central :/   [4.1.66.Final](https://github.com/netty/netty/releases/tag/netty-4.1.66.Final)

**Comment by zyclonite** [comment]
@DemonicTutor i guess you used another email so the eca failed

**Comment by DemonicTutor** [comment]
@zyclonite oh thanks - just checked out in gitkraken and usually it gets this stuff right but its not even signed... ill forcepush it correctly

**Comment by vietj** [comment]
I will create a CQ for this

**Comment by DemonicTutor** [comment]
@vietj whats a CQ ?

**Comment by DemonicTutor** [comment]
also created a PR for branch 4.1 just in case: https://github.com/vert-x3/vertx-dependencies/pull/64

**Comment by vietj** [comment]
Eclipse Contribution Questionnaire

**Comment by vietj** [comment]
- Netty 4.1.66.Final         : https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23628
- works-with                 : https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23629

**Comment by vietj** [comment]
- Netty 4.1.66.Final         : https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23628
- works-with                 : https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23629

**Comment by vietj** [comment]
see https://github.com/vert-x3/issues/issues/581

**Pull request closed without merging**
